# Generated by Django 2.0.3 on 2018-04-03 03:25

from django.db import migrations, models
import picManager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='picEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('likes', models.PositiveIntegerField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('sha256', models.CharField(default=picManager.models.picEntry._createHash, max_length=64)),
            ],
        ),
    ]
