# Generated by Django 2.0.3 on 2018-04-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picManager', '0002_auto_20180403_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picentry',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
