# Generated by Django 2.0.3 on 2018-04-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picManager', '0004_picentry_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField()),
                ('contents', models.CharField(max_length=500)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='picentry',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='picentry',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='picentry',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='associatePic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picManager.picEntry'),
        ),
    ]
