# Generated by Django 2.0.3 on 2018-04-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picManager', '0005_auto_20180405_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('number_we_have', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
