# Generated by Django 2.0.3 on 2018-04-07 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picManager', '0007_auto_20180407_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picentry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
