# Generated by Django 2.0.3 on 2018-04-08 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picManager', '0008_auto_20180407_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='pictureLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picManager.picEntry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
